# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference.
version: 2.1
orbs:
  tfsec: mycodeself/tfsec-orb@1.0.5
jobs:
  scan-example:
    executor: tfsec/default
    steps:
      - checkout
      - tfsec/scan
workflows:
  analyze-tf-code:
    jobs:
      - scan-example
 
